<?php

if (!defined('PRODUCT_MODULE_SCREEN_NAME')) {
    define('PRODUCT_MODULE_SCREEN_NAME', 'product');
}

if (!defined('PRODUCT_MODULE_COUPON_SCREEN_NAME')) {
    define('PRODUCT_MODULE_COUPON_SCREEN_NAME', 'product_coupon');
}

if (!defined('HISTORY_MODULE_PRODUCT_CATEGORY')) {
    define('HISTORY_MODULE_PRODUCT_CATEGORY', 'HISTORY_PRODUCT_CATEGORY');
}

if (!defined('HISTORY_MODULE_PRODUCT')) {
    define('HISTORY_MODULE_PRODUCT', 'HISTORY_MODULE_PRODUCT');
}